import { PinPadResult } from "../saletran/services/models/pinpad-result";

export class ExchCardTndr {
    public rslt:PinPadResult = new PinPadResult();
    public Result: string = '';
    public ResponseText: string = '';
    // public eMV_TAG_8A: string = '' = '';
    // public eMV_TAG_82: string = '' = '';
    // public eMV_TAG_5F34: string = '' = '';
    // public eMV_TAG_5F2A: string = '' = '';
    // public eMV_TAG_50: string = '' = '';
    // public eMV_TAG_4F: string = '' = '';
    // public tID: string = '' = '';
    // public mID: string = '' = '';
    // public mIME_TYPE: string = '' = '';
    // public sIGNATUREDATA: string = '' = '';
    // public vSP_TRXID: string = '' = '';
    // public vSP_RESULTDESC: string = '' = '';
    // public vSP_CODE: string = '' = '';
    // public pOS_RECON: string = '' = '';
    // public tRAINING_MODE: string = '' = '';
    // public eMV_TAG_9F02: string = '' = '';
    // public eMV_TAG_9F03: string = '' = '';
    // public eMV_TAG_9F07: string = '' = '';
    // public eMV_TAG_9F0D: string = '' = '';
    // public eMV_TAG_9F09: string = '' = '';
    // public eMV_TAG_9F08: string = '' = '';
    // public eMV_TAG_9F21: string = '' = '';
    // public eMV_TAG_84: string = '' = '';
    // public tAC_ONLINE: string = '' = '';
    // public tAC_DENIAL: string = '' = '';
    // public tAC_DEFAULT: string = '' = '';
    // public eMV_CHIP_INDICATOR: string = '' = '';
    // public eMV_CVM: string = '' = '';
    // public bATCH_TRACE_ID: string = '' = '';
    // public eMV_MODE: string = '' = '';
    // public eMV_TAG_9F36: string = '' = '';
    // public eMV_TAG_9F34: string = '' = '';
    // public eMV_TAG_9F27: string = '' = '';
    // public eMV_TAG_9F26: string = '' = '';
    // public eMV_TAG_9F1A: string = '' = '';
    // public eMV_TAG_9F12: string = '' = '';
    // public eMV_TAG_9F10: string = '' = '';
    // public eMV_TAG_9F0F: string = '' = '';
    // public eMV_TAG_9F0E: string = '' = '';
    // public eMV_TAG_9F37: string = '' = '';
    // public tRANS_TIME: string = '' = '';
    // public tRANS_DATE: string = '' = '';
    // public rECEIPT_DATA: string = '' = '';
    // public cASHBACK_AMNT: number = 0;
    // public fSA_AMOUNT: number = 0;
    // public dIFF_AMOUNT_DUE: number = 0;
    // public oRIG_TRANS_AMOUNT: number = 0;
    // public aPPROVED_AMOUNT: number = 0;
    // public aVAILABLE_BALANCE: number = 0;
    // public aUTH_CODE: string = '' = '';
    // public aCCT_NUM: string = '' = '';
    // public eBT_TYPE: string = '' = '';
    // public tIP_AMOUNT: number = 0;
    // public cARD_ABBRV: string = '' = '';
    // public pAYMENT_MEDIA: string = '' = '';
    // public pAYMENT_TYPE: string = '' = '';
    // public cARD_TOKEN: string = '' = '';
    // public lPTOKEN: number = 0;
    // public cTROUTD: number = 0;
    // public tROUTD: number = 0;
    // public iNTRN_SEQ_NUM: string = '' = '';
    // public tRANS_SEQ_NUM: string = '' = '';
    // public rRN: string = '' = '';
    // public pPCV: string = '' = '';
    // public eMV_TAG_9F33: string = '' = '';
    // public fS_AVAIL_BALANCE: number = 0;
    // public cARD_ENTRY_MODE: string = '' = '';
    // public tERMID: string = '' = '';
    // public mERCHID: string = '' = '';
    // public sAF_NUM: number = 0;
    // public eMBOSSED_ACCT_NUM: number = 0;
    // public bANK_USERDATA: string = '' = '';
    // public aUTHNWNAME: string = '' = '';
    // public aUTHNWID: string = '' = '';
    // public rESPONSE_CODE: string = '' = '';
    // public hOST_RESPCODE: string = '' = '';
    // public cB_AVAIL_BALANCE: number = 0;
    // public aUTH_RESP_CODE: string = '' = '';
     public CUSTOMER_ZIP: string = '';
     public MERCH_REF: string = '';
     public MERCH_DECL: string = '';
     public CVV2_CODE: string = '';
     public AVS_CODE: string = '';
     public CARD_EXP_YEAR: number = 0;
     public CARD_EXP_MONTH: number = 0;
     public CARDHOLDER: string = '';
     public EMV_REVERSAL_TYPE: number = 0;
     public PRESWIPED: number = 0;
     public EMV_TAG_9F35: string = '';
     public INVOICE: string = '';
    public FIRST6_LAST4: string = '';
    public MACHINE_NAME: string = '';
    public RESPONSE_XML: string = '';
    public ticketTenderId: number = 0;
    public transactionId: number = 0;


      resultCode: string = '';
  TerminationStatus: string = '';
  Counter: number = 0;
  TRANS_SEQ_NUM: string = '';
  INTRN_SEQ_NUM: string = '';
  TROUTD: string = '';
  CTROUTD: string = '';
  lPTOKEN: string = '';
  CARD_TOKEN: string = '';
  PAYMENT_TYPE: string = '';
  PAYMENT_MEDIA: string = '';
  PPCV: string = '';
  CARD_ABBRV: string = '';
  sUB_CARD_TYPE: string = '';
  EBT_TYPE: string = '';
  ACCT_NUM: string = '';
  AUTH_CODE: string = '';
  AVAILABLE_BALANCE: number = 0;
  APPROVED_AMOUNT: number = 0;
  ORIG_TRANS_AMOUNT: number = 0;
  DIFF_AMOUNT_DUE: number = 0;
  FSA_AMOUNT: number = 0;
  CASHBACK_AMNT: number = 0;
  TIP_AMOUNT: number = 0;
  FS_AVAIL_BALANCE: number = 0;
  CB_AVAIL_BALANCE: number = 0;
  CARD_ENTRY_MODE: string = '';
  AUTH_RESP_CODE: string = '';
  HOST_RESPCODE: string = '';
  HESPONSE_CODE: string = '';
  AUTHNWID: string = '';
  AUTHNWNAME: string = '';
  BANK_USERDATA: string = '';
  EMBOSSED_ACCT_NUM: string = '';
  SAF_NUM: string = '';
  MERCHID: string = '';
  TERMID: string = '';
  RECEIPT_DATA: string = '';
  TRANS_DATE: string = '';
  TRANS_TIME: string = '';
  BATCH_TRACE_ID: string = '';
  TRAINING_MODE: string = '';
  POS_RECON: string = '';
  VSP_CODE: string = '';
  VSP_RESULTDESC: string = '';
  VSP_TRXID: string = '';
  SIGNATUREDATA: string = '';
  MIME_TYPE: string = '';
  EMV_TAG_4F: string = '';
  EMV_TAG_50: string = '';
  EMV_TAG_5F2A: string = '';
  EMV_TAG_5F34: string = '';
  EMV_TAG_82: string = '';
  EMV_TAG_8A: string = '';
  EMV_TAG_95: string = '';
  EMV_TAG_9A: string = '';
  EMV_TAG_9B: string = '';
  EMV_TAG_9C: string = '';
  EMV_TAG_9F02: string = '';
  EMV_TAG_9F03: string = '';
  EMV_TAG_9F07: string = '';
  EMV_TAG_9F0D: string = '';
  EMV_TAG_9F0E: string = '';
  EMV_TAG_9F0F: string = '';
  EMV_TAG_9F10: string = '';
  EMV_TAG_9F12: string = '';
  EMV_TAG_9F1A: string = '';
  EMV_TAG_9F26: string = '';
  EMV_TAG_9F27: string = '';
  EMV_TAG_9F34: string = '';
  EMV_TAG_9F36: string = '';
  EMV_TAG_9F37: string = '';
  EMV_MODE: string = '';
  EMV_CVM: string = '';
  EMV_CHIP_INDICATOR: string = '';
  TAC_DEFAULT: string = '';
  TAC_DENIAL: string = '';
  TAC_ONLINE: string = '';
  EMV_TAG_84: string = '';
  EMV_TAG_9F21: string = '';
  EMV_TAG_9F08: string = '';
  EMV_TAG_9F09: string = '';
  EMV_TAG_9F33: string = '';
  MachineName: string = '';
  PinPadSerialNum: string = '';
  ResponseXml: string = '';
  VFONE_WEBSRV_VER: string = '';
  

}

export class SaveExchCardTndrResult {
    public exchCardTndrId: number = 0;
    public ticketTenderId: number = 0;
}

export class SaveExchCardTndrResultModel {
    public data: SaveExchCardTndrResult = new SaveExchCardTndrResult();
    public message: string = '';
    public success: boolean = false;
}